language: php

php:
- "7.0"
- "7.1"

sudo: false

before_script:
- phpize && ./configure --enable-cssmin && make && make install

script:
- export REPORT_EXIT_STATUS=1
- export TEST_PHP_EXECUTABLE=sapi/cli/php
- export NO_INTERACTION=1
- make test

notifications:
  email: false
